/**
 * scripts/add-thesis-john-authorship.ts
 *
 * Adds Jude C.R. Begay's thesis "The Apostolic Authorship of the Fourth
 * Gospel: A Reassessment of the External and Internal Evidence" as a
 * long-form article in Sanity.
 *
 * Author: Jude
 * Category: Theology
 * Slug:    apostolic-authorship-fourth-gospel
 *
 * Usage:  npx tsx scripts/add-thesis-john-authorship.ts
 */

import { createClient } from "@sanity/client";
import * as dotenv from "dotenv";
import * as path from "path";

dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });

const client = createClient({
  projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID!,
  dataset: "production",
  apiVersion: "2024-01-01",
  useCdn: false,
  token: process.env.SANITY_API_WRITE_TOKEN,
});

type Section = { heading?: string; level?: 2 | 3; paragraphs: string[] };

const TITLE =
  "The Apostolic Authorship of the Fourth Gospel: A Reassessment of the External and Internal Evidence";
const SLUG = "apostolic-authorship-fourth-gospel";

const EXCERPT =
  "Who wrote the Fourth Gospel? A reassessment of the external and internal evidence, arguing that the traditional identification of John son of Zebedee as the eyewitness author remains the most historically defensible position.";

// ─── Content ────────────────────────────────────────────────────────────
// Each section becomes a block of paragraphs prefixed by an optional heading.
const SECTIONS: Section[] = [
  {
    paragraphs: [
      "Who wrote the Fourth Gospel? At first glance this may appear to be a question of purely academic interest — a matter of ancient sources, fragmentary texts and scholarly debate with little bearing on anything beyond the seminar room. But the question is far more consequential than that. The Gospel of John makes claims of the most extraordinary kind — that the Word who was in the beginning with God and was God became flesh and dwelt among us, that the glory of the eternal Son was seen with human eyes, that the one who hung on a Roman cross was the lamb of God who takes away the sin of the world. These are not modest theological proposals. They are either the most significant claims ever made about a human being or they are of no ultimate value at all. And the question of who wrote the gospel that makes these claims bears directly on how seriously they deserve to be taken. If the Fourth Gospel is the eyewitness testimony of an apostle who walked with Jesus, who reclined beside him at the Last Supper, who stood at the foot of the cross and watched him die — then it demands to be read as the witness of one who was there, whose testimony is grounded in direct personal experience of the events it describes. If it is instead the theological construction of a late Hellenistic community at a considerable remove from the historical Jesus, shaped more by the religious environment of the ancient world than by the memory of eyewitnesses, then it must be read in an entirely different register. The authorship question is therefore not a peripheral academic concern — it goes to the heart of how we read the gospel and how we understand the Jesus it presents.",
      "The question has generated an enormous body of scholarly literature, shaped decisively in the modern period by Wilhelm Bousset and the history of religions school. Bousset's Kyrios Christos, first published in 1913, argued that the high Christology of the New Testament — the worship of Jesus as divine Lord — was not original to the earliest Palestinian Jewish community around Jesus but developed in the Hellenistic Gentile Christian communities of Antioch, Damascus and Tarsus. On this reading the Fourth Gospel, with its Logos prologue, its explicit identification of Jesus with God and its developed theological sophistication, is most naturally understood as a late Hellenistic community document rather than apostolic eyewitness testimony. The shadow of this framework has fallen across discussions of Johannine authorship ever since, creating the assumption that traditional apostolic authorship is historically naive and that the burden of proof lies heavily against it. This thesis argues that the assumption is unwarranted and that the framework which generates it has not withstood the scrutiny of subsequent scholarship.",
      "The argument proceeds through five chapters. The first examines the history of religions school and its limitations, engaging the work of Bousset alongside the critical responses of Larry Hurtado and George Eldon Ladd, and argues that the developmental model of Christology on which critical authorship conclusions depend has been shown to rest on historically insecure foundations. The second and third chapters examine the external and internal evidence for authorship respectively — the patristic testimony of Irenaeus and the witness of the gospel itself — building a cumulative case from multiple independent lines of evidence that converge on the same conclusion. The fourth chapter situates that conclusion within its most natural historical context, arguing that the apostolic environment of Ephesus provides the key to understanding how the gospel's eyewitness testimony was preserved, shaped and transmitted. The fifth chapter weighs the two most serious scholarly positions against each other — the traditional identification of John son of Zebedee and Richard Bauckham's influential Elder John hypothesis — and argues that when the evidence is properly assessed the traditional position remains the most historically defensible.",
      "This thesis does not claim to settle the authorship question beyond reasonable doubt. The nature of the evidence does not permit that degree of certainty, and intellectual honesty requires acknowledging as much from the outset. What it claims is more modest but no less significant — that when the Boussetian framework is set aside, when the evidence is examined carefully and when the reliability and proximity of the witnesses are properly weighed, the traditional identification of John son of Zebedee as the eyewitness author of the Fourth Gospel is the most historically defensible position available. The one who wrote 'we saw His glory' was most plausibly among those who did.",
    ],
  },
  {
    heading: "Chapter 1: The History of Religions School and Its Limitations",
    level: 2,
    paragraphs: [],
  },
  {
    heading: "1.1 Introduction — Why Bousset Still Matters",
    level: 3,
    paragraphs: [
      "Any serious engagement with the authorship of the Fourth Gospel must reckon with the intellectual legacy of Wilhelm Bousset and the history of religions school he represented. The question of who wrote the Fourth Gospel has never been asked in a vacuum — it has been asked within a set of assumptions about how early Christianity developed, how its Christology emerged and what kind of document the Fourth Gospel is. Those assumptions were shaped more profoundly by Bousset's Kyrios Christos, first published in 1913, than by almost any other single work of modern scholarship. As Larry Hurtado acknowledges, Kyrios Christos remains 'unrivaled in weight, scope, and influence' as a study of early Christ-devotion — even its critics are reacting to it or building on its framework. To engage seriously with the authorship question is therefore to engage seriously with Bousset, because the framework he established has shaped the terms of the debate for over a century.",
      "The relevance of Bousset to the authorship question is not always made explicit in discussions of the Fourth Gospel, but it operates as a powerful background assumption. If Bousset is right — if the high Christology of the New Testament is a product of Hellenistic community development rather than original apostolic testimony, if the Kyrios title and the elevated devotion to Jesus as divine Lord emerged in Gentile Christian communities at a remove from the historical Jesus — then the Fourth Gospel with its Logos prologue, its explicit identification of Jesus with God and its developed 'I am' sayings is most naturally read as a late Hellenistic community document rather than the eyewitness testimony of an apostle. The critical tendency to date the gospel late, to posit elaborate community composition theories and to treat apostolic authorship as historically naive flows directly from the Boussetian framework even when Bousset is not explicitly cited. It is therefore necessary to examine that framework carefully, to understand its arguments and then to assess the degree to which it has withstood the scrutiny of subsequent scholarship.",
    ],
  },
  {
    heading: "1.2 Bousset's Argument — The Developmental Model",
    level: 3,
    paragraphs: [
      "Bousset's central thesis in Kyrios Christos is that the devotion given to Jesus as a divine figure — what he calls the Christ cult — did not originate in the earliest Palestinian Jewish community around Jesus but developed in the Hellenistic Gentile Christian communities of Antioch, Damascus and Tarsus before Paul. His argument proceeds through a careful analysis of the titles applied to Jesus in the New Testament, tracing what he sees as a staged developmental trajectory from a primitive Palestinian Christology to an elevated Hellenistic one.",
      "In the primitive Palestinian Jewish community, Bousset argues, Jesus was understood primarily through the title Son of Man — a Jewish apocalyptic category rooted in Daniel 7 and the Enochic literature. This was a high but essentially Jewish way of understanding Jesus, tied to specific expectations about eschatological vindication and the coming kingdom of God. As the gospel moved into the Hellenistic world, however, this title became, in Bousset's words, 'incapable of being understood' in communities where the Jewish apocalyptic background was unfamiliar. New titles and new categories were needed, and it was in the Hellenistic Gentile communities — not in Jerusalem — that the decisive transformation occurred.",
      "The key development for Bousset is the emergence of the Kyrios title — the designation of Jesus as Lord in the full divine sense. Bousset argues that this title was not used of Jesus in the Palestinian Jewish community but was taken over in the Hellenistic communities from the religious environment of the ancient world where Kyrios was commonly applied to divine figures and cult deities. The Christ cult — the worship of Jesus as a divine Lord — was therefore not original to the apostolic circle but was a product of the encounter between the Jesus tradition and the religious culture of the Hellenistic world. As Hurtado summarizes Bousset's position, the Christ cult 'does not go back to the original groups of Jewish Palestine' but emerges in Hellenistic Gentile Christianity where Jesus becomes the divine Kyrios under the influence of pagan religious categories.",
      "The implications of this developmental model for the Fourth Gospel are direct and significant. Bousset himself engages the Johannine literature, treating the Fourth Gospel as a product of this developmental trajectory rather than as independent apostolic testimony. In his discussion of the Kyrios title in John he argues that the author of the Fourth Gospel 'borrowed' the title from the synoptic tradition and 'otherwise avoids' it — treating the gospel as a secondary literary construction working with inherited theological categories rather than preserving direct eyewitness memory. The Logos theology of the prologue, the explicit identification of Jesus with God in 1:1 and 20:28, the developed 'I am' sayings — all of these are most naturally read within the Boussetian framework as the theological elaboration of a Hellenistic community at a considerable remove from the historical Jesus rather than as the testimony of one who was there.",
      "This framework has proven remarkably durable. As Hurtado notes, many subsequent scholars followed Bousset's evolutionary model — assuming a staged development from low to high Christology and treating the Fourth Gospel's elevated theology as evidence of lateness and community composition. Reginald Fuller and others working on Christological titles built on Bousset's framework even when modifying it in detail. More recently Maurice Casey has updated the Boussetian argument, claiming that the divinization of Jesus in Johannine Christianity is a late development caused by Gentile influence and the breakdown of Jewish identity. The specific conclusions differ but the underlying assumption is the same — high Christology is late, developmental and incompatible with early eyewitness apostolic origin.",
    ],
  },
  {
    heading: "1.3 The Collapse of the Developmental Model — Hurtado's Challenge",
    level: 3,
    paragraphs: [
      "The Boussetian framework has not gone unchallenged, and in recent decades it has faced increasingly powerful criticism from scholars who argue that the evidence points in precisely the opposite direction from what Bousset assumed. The most comprehensive and influential of these challenges has come from Larry Hurtado, whose Lord Jesus Christ represents a systematic dismantling of the developmental model on both historical and exegetical grounds.",
      "Hurtado begins by reframing the question. Rather than asking how the simple Jewish message about Jesus became elevated into Hellenistic divine Lordship, he asks why devotion to Jesus as a divine figure emerged at all within the fiercely exclusivist monotheistic matrix of Second Temple Judaism. Hurtado argues that the Jewish religious environment of the first century was so thoroughly committed to the exclusive worship of the God of Israel that the incorporation of Christ into early Christian devotional practice 'has no real analogy in the Jewish tradition of the period.' This is a point of fundamental importance. If Bousset were right that the Christ cult was a product of Hellenistic influence, we would expect it to have emerged gradually and naturally as the gospel moved into the Gentile world. But Hurtado's analysis shows that the devotional pattern of worshipping Jesus alongside God is present remarkably early — earlier than Bousset's developmental model can accommodate — and that it emerged within Jewish Christian communities, not in Hellenistic Gentile ones.",
      "This directly challenges Bousset's assumed developmental stages. Hurtado notes that Bousset artificially separated Palestinian Jewish Christianity from Hellenistic Gentile Christianity, treating the former as the preserve of a lower Christology and the latter as the environment in which elevated devotion to Jesus developed. But this separation does not hold up under scrutiny. The evidence from Paul's earliest letters — which Hurtado dates to within two decades of the crucifixion — already reflects a fully developed devotional pattern of worshipping Jesus alongside God, praying to Jesus, singing hymns to Jesus and invoking his name. This is not a late Hellenistic development — it is present at the earliest recoverable moment of the Christian movement, within the lifetime of eyewitnesses to the historical Jesus.",
      "Hurtado's critique of Maurice Casey is particularly pointed and directly relevant to the Johannine authorship question. Casey argues that the divinization of Jesus in Johannine Christianity is a late development caused by Gentile influence and the breakdown of Jewish identity. Hurtado responds that Casey 'fails to see the significance of the Christian devotional and worship practices evident decades earlier.' This is a decisive empirical point — if worship of Jesus as divine is already present in the earliest recoverable evidence, it cannot be a late invention of Johannine Christianity. The high Christology of the Fourth Gospel does not require a late date or a Hellenistic community composition because the devotional pattern it reflects was already present in the earliest Jewish Christian communities. Casey's argument, like Bousset's before it, assumes the conclusion it needs to prove.",
    ],
  },
  {
    heading: "1.4 Ladd's Mediating Contribution",
    level: 3,
    paragraphs: [
      "George Eldon Ladd occupies a mediating position in this debate that is worth acknowledging before drawing conclusions. Ladd takes historical criticism seriously and engages with the Hellenistic background of Johannine theology without dismissing it, but he reaches conclusions that support the traditional authorship position rather than undermining it.",
      "On the Logos concept of the prologue Ladd acknowledges the Hellenistic background — the Stoic Logos as the rational principle pervading the universe, the Philonic Logos as a divine intermediary — but argues that 'the present tendency is to interpret the term against its Old Testament background' rather than its Hellenistic one, noting that its roots lie in 'debar Yahweh, the creative and revealing Word of God, by which the heavens and earth were made and the prophets inspired.' The author of the Fourth Gospel did not borrow the Logos concept from Hellenistic philosophy — he seized upon a term widely known in both worlds to communicate a fundamentally Jewish theological reality about the God of Israel becoming flesh in the person of Jesus.",
      "On the question of pre-existence and high Christology Ladd makes the point that would become central to Hurtado's more systematic argument — that 'pre-existence was a Jewish idea' not a Hellenistic importation, rooted in Jewish apocalyptic literature and implicit in Jesus's own use of the Son of Man title. His conclusion is direct: 'The Johannine Jesus only affirms more explicitly what is implicit in the Synoptics.' This is not Hellenistic theological inflation at a remove from history — it is the fullest expression of a Christology already present in the earliest Jesus tradition, articulated by one who had decades to meditate on what he had witnessed firsthand.",
    ],
  },
  {
    heading: "1.5 Implications for Authorship — Clearing the Ground",
    level: 3,
    paragraphs: [
      "The significance of this debate for the authorship question can now be stated clearly. The Boussetian framework functions as a kind of invisible pressure on discussions of Johannine authorship — it creates the assumption that the high Christology of the Fourth Gospel is evidence of lateness and community composition, and that apostolic eyewitness authorship is therefore historically implausible. Once that framework is dismantled the pressure it exerts on the authorship question dissolves.",
      "If Hurtado is right that devotion to Jesus as divine Lord is present in the earliest recoverable evidence within Jewish Christian communities — if it is not a late Hellenistic development but an early Jewish response to what the first witnesses believed they had experienced — then the high Christology of the Fourth Gospel is entirely compatible with eyewitness apostolic authorship. An aged apostle at Ephesus, reflecting across decades on what he had witnessed, articulating in the fullest possible terms the theological significance of what he had seen — this is not a historically implausible figure. It is precisely the kind of figure the evidence produces when the Boussetian framework is set aside and the evidence is allowed to speak for itself.",
      "The history of religions school represented by Bousset was a remarkable scholarly achievement whose influence on New Testament studies cannot be overstated. But its central developmental model — the assumption that high Christology is late, Hellenistic and incompatible with early apostolic origin — has not withstood the scrutiny of subsequent scholarship. The framework that made critical authorship conclusions seem historically inevitable has been shown to rest on assumptions that the evidence does not support. With that framework cleared, the authorship question can be approached on its own terms, and it is to that question that the remaining chapters of this thesis turn.",
    ],
  },
  {
    heading: "Chapter 2: The External Evidence",
    level: 2,
    paragraphs: [],
  },
  {
    heading: "2.1 The Testimony of Irenaeus",
    level: 3,
    paragraphs: [
      "Any serious investigation into the authorship of the Fourth Gospel must reckon with the external evidence left to us by the early church fathers. Among these witnesses, Irenaeus of Lyon stands as the most important and most reliable. Writing in the late second century, Irenaeus explicitly identifies the author of the Fourth Gospel as John, the disciple of the Lord. His statement in Against Heresies is unambiguous: 'Afterwards, John, the disciple of the Lord, who also had leaned upon His breast, did himself publish a Gospel during his residence at Ephesus in Asia.' This is not a casual or incidental claim — Irenaeus makes it deliberately and with evident familiarity with the Johannine tradition. Particularly noteworthy is his identification of the author with the Beloved Disciple, the one who leaned upon the breast of the Lord at the Last Supper, connecting the external testimony directly to the internal witness of the gospel itself.",
      "What gives Irenaeus's testimony particular weight is not merely its antiquity but its source. Irenaeus himself personally knew Polycarp of Smyrna, whom he describes as one who 'was not only instructed by apostles, and conversed with many who had seen Christ, but was also, by apostles in Asia, appointed bishop of the Church in Smyrna.' Irenaeus is careful to note that he himself saw Polycarp in his own early youth, establishing a direct personal connection to this chain of apostolic tradition. Given the Ephesian context Irenaeus has already established, the apostles in Asia through whom Polycarp was instructed points directly to John. This creates a remarkably short chain of living memory — Irenaeus to Polycarp to John himself. In an age before mass literacy and widespread documentation, this kind of direct personal chain of testimony carries significant historical weight. Irenaeus is not repeating a rumor or a distant tradition — he is reporting what he received from a man who stood in direct personal relationship with the apostolic circle at Ephesus.",
      "The personal depth of this connection is further illuminated by Irenaeus's Letter to Florinus, preserved in Eusebius's Ecclesiastical History. There Irenaeus writes with striking personal specificity about his childhood memories of Polycarp, recalling that the blessed Polycarp 'had heard directly from eyewitnesses of the Word of life and reported in full harmony with scripture,' and that he himself had 'listened eagerly to these things' and noted them 'not on paper but in my heart.' This is not the language of formal theological transmission — it is the language of living personal memory. Irenaeus is not citing a document or repeating a received tradition at arm's length. He is recalling what he heard as a boy from a man who stood in direct personal relationship with the apostolic circle at Ephesus. The emotional specificity and personal vividness of this recollection lends it a quality of authenticity that is difficult to dismiss or manufacture.",
      "Furthermore Irenaeus preserves a striking detail about John at Ephesus that bears the marks of authentic personal memory rather than invented tradition. He recounts that those who heard from Polycarp remembered that 'John, the disciple of the Lord, going to bathe at Ephesus, and perceiving Cerinthus within, rushed out of the bath-house without bathing.' This vivid and specific anecdote, transmitted through Polycarp, independently corroborates John's presence at Ephesus and illustrates the kind of living personal memory that was circulating through Polycarp to Irenaeus. Such details are not the stuff of legend — they are the texture of real historical recollection.",
      "This point deserves emphasis because it is sometimes underplayed in critical scholarship. The tendency in much modern Johannine scholarship has been to privilege documentary analysis over chains of personal testimony, but this reflects a modern historiographical bias more than a sound assessment of ancient evidence. When a second century bishop tells us he heard from Polycarp who knew John, that testimony deserves to be taken seriously on its own terms rather than dismissed in favor of later and more complex hypotheses.",
      "Irenaeus's testimony is further corroborated by other early sources. The Muratorian Fragment, generally dated to the late second century, also attributes the Fourth Gospel to John and describes a process of communal verification among the apostles and disciples before its publication. While the Muratorian Fragment raises its own critical questions, its independent attestation of Johannine authorship strengthens the case that this was not a tradition invented by Irenaeus but one that was widely held in early Christianity.",
    ],
  },
  {
    heading: "2.2 The Papias Fragment and the Problem of Eusebius",
    level: 3,
    paragraphs: [
      "The primary challenge to the Irenaean tradition of apostolic authorship comes from a fragment of Papias of Hierapolis, preserved in Eusebius's Ecclesiastical History. Richard Bauckham in particular has built his influential Elder John hypothesis upon this fragment, arguing that Papias distinguishes between two figures both named John — the apostle son of Zebedee and a separate John the Elder — and that it is this second John who authored the Fourth Gospel. While Bauckham's argument has gained considerable traction in contemporary Johannine scholarship, a careful reading of the primary text reveals that the two Johns hypothesis is not Papias's own claim but rather Eusebius's editorial inference imposed upon it.",
      "The Papias fragment as preserved by Eusebius reads as follows: 'Along with the interpretations, I shall not hesitate to add all that I ever learned and carefully remembered from the elders, for I am sure of its truth. Unlike most, I did not delight in those who say much but in those who teach the truth; not in those who recite the commandments given by the Lord. And whenever anyone came who had been a follower of the elders, I asked about their words: what Andrew or Peter had said, or Philip or Thomas or James or John or Matthew or any other of the Lord's disciples, and what Aristion and the presbyter John, disciples of the Lord, were still saying. For I did not think that information from books would help me as much as the word of a living, surviving voice.'",
      "It is critical to observe what Papias himself actually says here and what he does not say. Papias mentions John twice — once in a list of the Lord's disciples alongside Peter, Philip, Thomas, James and Matthew, and once alongside Aristion as one whose words were still being circulated. Papias does not himself draw any distinction between these two references to John, nor does he explicitly identify them as two separate individuals. The inference that these references point to two distinct Johns is not Papias's conclusion — it is Eusebius's.",
      "Eusebius makes his interpretive move explicitly and transparently. Immediately following the Papias quotation he writes: 'It should be noted that twice Papias includes the name of John, the first listed with Peter, James, Matthew, and the other apostles; the second in another non apostolic group, putting Aristion first and clearly calling John a presbyter. This confirms the truth of the story that two men in Asia had the same name and that there are two tombs at Ephesus, each called John's to this day.' This is Eusebius's own editorial commentary, not a conclusion that flows naturally or inevitably from the text itself. The words 'it should be noted' signal that Eusebius is making an argument, drawing an inference he wants his readers to accept.",
      "This distinction between what Papias says and what Eusebius concludes from it is of fundamental importance for the authorship question. Bauckham's Elder John hypothesis, influential as it is, ultimately rests not on Papias's own testimony but on Eusebius's reading of that testimony. And as we have already seen, Eusebius is not a disinterested historian in this matter. He was deeply uncomfortable with the apostolic authorship of Revelation and its millenarian implications, and locating a second John at Ephesus conveniently resolved that theological problem. A historian with a motivated interest in finding two Johns reads a text that mentions John twice and concludes there must be two Johns — this is precisely the kind of circular reasoning that should give careful scholars pause.",
      "The contrast with Irenaeus is instructive. Irenaeus, writing considerably closer to the events in question and drawing on a direct personal chain of memory through Polycarp, shows no awareness of any distinction between the apostle John and a separate John the Elder. For Irenaeus there is simply John, the disciple of the Lord, the Beloved Disciple, the author of the Fourth Gospel, resident at Ephesus. If a second John of sufficient prominence to author the Fourth Gospel had existed at Ephesus, it is difficult to explain why Irenaeus — who had strong personal connections to the Ephesian tradition through Polycarp — would have been entirely unaware of him. The simpler and more historically defensible explanation is that there was one John at Ephesus, that Papias mentions him twice without intending to distinguish two separate figures, and that Eusebius has read his own theological agenda into the text.",
      "It is also worth noting the context in which Eusebius preserves the Papias fragment. Eusebius is not a neutral transmitter of earlier sources — he is a fourth century historian constructing a narrative of orthodox succession with clear ecclesiastical and theological interests. His Ecclesiastical History is a remarkable achievement but it is not an unbiased documentary record. When Eusebius tells us what a second century text means we are entitled to ask what he had to gain from that particular reading, and in the case of the two Johns the answer is clear.",
      "None of this is to say that Bauckham's hypothesis is without merit or that the question is entirely closed. The possibility that Papias does intend two distinct figures cannot be ruled out entirely. But the burden of proof lies with those who would overturn the consistent and early Irenaean tradition on the basis of an inference drawn by a later and demonstrably interested historian from an ambiguous text. When the evidence is weighed carefully the external testimony points toward one John at Ephesus — the disciple of the Lord, the Beloved Disciple, the apostle — as the source and author of the Fourth Gospel.",
    ],
  },
  {
    heading: "Chapter 3: The Internal Evidence",
    level: 2,
    paragraphs: [],
  },
  {
    heading: "3.1 The Eyewitness Voice — The Prologue and the \"We\" of 1:14",
    level: 3,
    paragraphs: [
      "While the external testimony of Irenaeus provides a strong historical anchor for the traditional authorship of the Fourth Gospel, the gospel itself contains internal evidence of comparable weight. From its very opening verses the Fourth Gospel presents itself not merely as a theological treatise but as the testimony of one who was there — one who saw, heard, and handled the Word of life. A careful reading of the prologue reveals an eyewitness voice embedded in the theological fabric of the text itself, and understanding that voice requires attending closely to both what the author says and the theological framework within which he says it.",
      "The prologue opens with a deliberate and unmistakable allusion to Genesis 1:1: 'In the beginning was the Word, and the Word was with God, and the Word was God. He was in the beginning with God. All things came into being through Him, and apart from Him not even one thing came into being that has come into being.' The author is not opening his gospel with a piece of Hellenistic philosophy — he is opening it with a claim about the God of Israel. As George Eldon Ladd observes, 'the present tendency is to interpret the term against its Old Testament background,' and T.W. Manson's assessment, cited approvingly by Ladd, is that 'the roots of the doctrine are in the Old Testament and that its main stem is debar Yahweh, the creative and revealing Word of God, by which the heavens and earth were made and the prophets inspired.' The Logos of the prologue is not the impersonal rational principle of Stoic philosophy nor the derived intermediary deity of Philo — it is the creative, revealing, personal Word of the God of Israel, now identified with Jesus of Nazareth.",
      "This identification has staggering implications that the author unpacks with theological precision. The Word was with God — a distinction of persons. The Word was God — a unity of essence. All things came into being through Him — the Word is the agent of creation itself. As Ladd notes, 'John uses the Logos idea to assert the deity of Jesus' while carefully preserving the distinction between the Word and the Father. The author is laying the groundwork for what would later be articulated as Trinitarian theology, and he is doing so not by importing categories from Hellenistic religion but by drawing out the deepest implications of Jewish monotheism itself. This is precisely the point Larry Hurtado makes when he argues that Christ-devotion 'emerged from within' the fiercely exclusivist monotheistic matrix of Second Temple Judaism — the incorporation of Christ into the devotional pattern of early Christianity, Hurtado contends, 'has no real analogy in the Jewish tradition of the period' and cannot be explained by appeal to Hellenistic influence. The prologue of the Fourth Gospel is the literary and theological expression of that remarkable development, rooted not in Hellenistic borrowing but in the most profound engagement with Jewish Scripture and theology.",
      "It is against this theological backdrop that the eyewitness claim of 1:14 must be understood in its full weight: 'And the Word became flesh, and dwelt among us; and we saw His glory, glory as of the only Son from the Father, full of grace and truth.' Three things demand attention here.",
      "First the incarnational claim itself — 'the Word became flesh.' Ladd notes that 'such an affirmation would amaze and refute all Hellenistic philosophical and gnostic dualisms that separated God from this world,' and that the author 'wishes to emphasize that it was God himself in the Word who entered human history, not as a phantom, but as a real man of flesh.' The one who existed before creation, the agent through whom all things came into being, entered human history as a real historical person. This is not mythology — it is a claim about a specific historical event.",
      "Second the tabernacle allusion — 'dwelt among us.' The Greek word skenoo means literally to tabernacle, to pitch a tent. As Ladd observes this is 'a biblical metaphor for God's presence,' implying 'that God himself was present in the flesh, in abasement.' The author is deliberately invoking the Shekinah glory of God dwelling among Israel in the wilderness — the same glory that filled the tabernacle, the same presence that accompanied Israel through the desert, the same God who told Moses 'I will dwell among the children of Israel' has now pitched his tent in human flesh. The theological continuity with the Old Testament is total and intentional.",
      "Third and most critically for the authorship question — 'we saw His glory.' This is not a literary device or a communal theological confession in the abstract. It is an eyewitness claim of the most profound order. The glory that filled the tabernacle, that Moses could not look upon directly, that Isaiah glimpsed in the temple and was undone by — this glory, the author says, we saw. The shift to first person plural is deliberate and significant. The author is embedding himself within a circle of eyewitnesses who stood in the physical presence of the incarnate Word and beheld His glory directly.",
      "This 'we' connects naturally to the apostolic community at Ephesus that stands behind the gospel. As we have already seen, Irenaeus locates John at Ephesus within a living community of apostolic testimony. The 'we' of 1:14 is not evidence of committee authorship or community composition — it is the voice of an eyewitness speaking from within and on behalf of the apostolic circle that shared his experience and vouches for his testimony. This reading is confirmed by the editorial note of 21:24 — 'we know that his testimony is true' — which we will examine in detail in section 3.5. The same apostolic 'we' that opens the gospel closes it.",
      "The connection to John 17 deepens this reading further. In his farewell prayer Jesus says 'Father, I desire that they also whom You have given Me may be with Me where I am, so that they may see My glory which You have given Me, for You loved Me before the foundation of the world.' The author of the prologue who declares 'we saw His glory' is claiming membership in the very circle Jesus prays will behold that eternal glory — the glory the Word had with the Father before creation. The one writing this gospel is not a distant theologian constructing a Christology from borrowed philosophical categories. He is a witness testifying to what he saw, interpreting what he saw through the deepest resources of Jewish Scripture, and connecting his eyewitness experience to the eternal reality of the pre-existent Word.",
      "Ladd's observation is worth restating in this context: 'The Johannine Jesus only affirms more explicitly what is implicit in the Synoptics.' The high Christology of the prologue is not a departure from the apostolic tradition — it is its fullest expression, articulated by one who had decades to meditate on what he had witnessed firsthand. This is exactly what we would expect from an aged apostle at Ephesus looking back across a lifetime of reflection on the glory he had seen with his own eyes.",
    ],
  },
  {
    heading: "3.2 The Beloved Disciple — Identity, Anonymity and Eyewitness Testimony",
    level: 3,
    paragraphs: [
      "At the heart of the Fourth Gospel's internal evidence for authorship stands the figure of the Beloved Disciple — the unnamed disciple who appears at the most intimate and theologically significant moments of Jesus's ministry, passion and resurrection. Understanding who this figure is and why he is presented the way he is represents perhaps the most important exegetical task in the entire authorship discussion. A careful reading of the Beloved Disciple passages reveals not a literary construct or a symbolic figure but a real historical eyewitness whose anonymity is itself a significant authorial signal.",
      "The Beloved Disciple makes his first appearance at 1:35 as one of two disciples who follow Jesus at the testimony of John the Baptist. As Richard Bauckham observes, this initial appearance 'is more significant than is usually noticed' because it makes the Beloved Disciple 'a witness of John's testimony to Jesus, as well as to the beginning of Jesus' ministry.' This is not an incidental detail — the author is establishing his eyewitness credentials from the very opening of the narrative, placing himself at the origin point of Jesus's public ministry. The Beloved Disciple is present from the beginning, hearing the Baptist's testimony that Jesus is the sacrificial lamb of God, and this detail will carry enormous weight when we reach the cross.",
      "From this first appearance the Beloved Disciple is present at the most intimate and theologically decisive moments of the gospel narrative. He reclines at Jesus's bosom at the Last Supper in 13:23, a position of extraordinary intimacy that mirrors the description of the Son in the bosom of the Father in 1:18 — a detail that is almost certainly intentional on the author's part. He stands at the foot of the cross in 19:26-27, the only male disciple present at the crucifixion. He runs to the empty tomb with Peter in 20:2-10, arriving first and believing. He recognizes the risen Jesus on the shore of the Sea of Tiberias in 21:7. At every turning point of the gospel story the Beloved Disciple is there — watching, witnessing, remembering.",
      "The climactic eyewitness claim comes at 19:35 in connection with the crucifixion: 'And he who has seen has testified, and his testimony is true; and he knows that he is telling the truth, so that you also may believe.' Bauckham rightly identifies this verse as the pivot around which the entire authorship question turns. He notes the crucial connection between 19:35 and 21:24 — 'in light of 21:24 in the final form of the Gospel, 19:35 explicitly portrays the beloved disciple as author of the Gospel.' The same figure who witnesses the flow of blood and water from the side of the crucified Jesus, confirming him as the true Passover lamb whose bones are not broken, steps forward here as the eyewitness author staking his credibility on what he personally saw. This is not theological elaboration after the fact — it is the testimony of one who was standing at the foot of the cross.",
      "Bauckham further observes a remarkable literary connection between 19:35 and both 1:14 and 20:31. He notes that only in 19:35 and 20:31 does the author address his readers directly in the second person — 'so that you also may believe' in 19:35, 'so that you may believe' in 20:31 — drawing attention to the author as author in a way that third person narrative normally does not. This second person address connects directly to the authorial 'we' of 1:14 that we examined in section 3.1. The voice that says 'we saw His glory' in the prologue, the voice that says 'he who has seen has testified' at the cross, and the voice that says 'so that you may believe' at the conclusion of the narrative are the same voice — the eyewitness author speaking from within and on behalf of the apostolic community that vouches for his testimony.",
      "The Passover lamb connection that Bauckham identifies deepens this reading further. The Beloved Disciple first appears hearing John the Baptist testify that Jesus is 'the lamb of God who takes away the sin of the world' in 1:29 and 1:35. His most explicit eyewitness claim comes at the cross where he witnesses the fulfillment of precisely that testimony — the true Passover lamb, bones unbroken, blood and water flowing from his side. As Bauckham puts it, the Beloved Disciple is present at the cross as 'the only male disciple who witnesses the key salvific event of the whole Gospel story, the hour of Jesus' exaltation, toward which the whole story from John the Baptist's testimony onward has pointed.' The narrative arc from 1:35 to 19:35 is not accidental — it is the carefully constructed testimony of an eyewitness who understood the theological significance of what he had seen from beginning to end.",
      "The anonymity of the Beloved Disciple is itself a significant authorial signal that has not always received the attention it deserves. Throughout the Fourth Gospel the author names his characters with specificity — Peter, Andrew, Philip, Thomas, Nathanael, Matthew and others are all identified by name. Yet the disciple who appears at the most intimate and significant moments of the narrative, the disciple whom Jesus loved, is never named. This consistent and deliberate anonymity is not an oversight — it is a convention. Ancient eyewitness authors sometimes signaled their own presence in the narrative through self-effacing anonymity rather than explicit self-identification, precisely because naming oneself directly would have felt presumptuous or would have undermined the objective credibility of the testimony. The author's anonymity is not evidence against his being a real historical figure — it is evidence of his authorial self-consciousness. He knows he is writing about himself and he chooses not to name himself, leaving the identification to be made by those who know him and can vouch for his testimony — which is precisely what 21:24 records.",
      "This reading of the Beloved Disciple as the anonymous eyewitness author is further confirmed by the process of elimination that the gospel itself invites. In chapter 21 seven disciples are present at the resurrection appearance on the Sea of Tiberias: Simon Peter, Thomas, Nathanael, the Sons of Zebedee, and two unnamed disciples. The Beloved Disciple is among these seven. The author never names himself throughout the gospel, which rules out those disciples he does name explicitly. Matthew wrote his own gospel, making it unlikely he is the unnamed BD. James son of Zebedee was martyred very early — Acts 12:2 places his death under Herod Agrippa around 44 AD — making it virtually impossible that he authored a gospel with such a developed tradition. That leaves John son of Zebedee as the most natural and historically defensible identification of the Beloved Disciple and therefore of the author of the Fourth Gospel — a conclusion that converges precisely with the external testimony of Irenaeus examined in Chapter 2.",
    ],
  },
  {
    heading: "3.3 The Process of Elimination — Chapter 21 and the Case for John Son of Zebedee",
    level: 3,
    paragraphs: [
      "The identity of the Beloved Disciple and therefore of the author of the Fourth Gospel can be approached not only through the direct eyewitness claims we have examined in sections 3.1 and 3.2 but through a careful process of elimination that the gospel itself invites. The resurrection appearance in John 21 provides the necessary data for this process, and when it is worked through carefully alongside the synoptic lists of the twelve and the early history of the apostolic church, the conclusion points with remarkable consistency toward John son of Zebedee.",
      "John 21 records a resurrection appearance of Jesus on the shore of the Sea of Tiberias to a specific group of seven disciples: 'Simon Peter, Thomas who was called Didymus, Nathanael of Cana of Galilee, the Sons of Zebedee, and two others of His disciples.' This is a precisely defined group. The Beloved Disciple is among these seven — he is the one who first recognizes Jesus on the shore in 21:7 and the one identified in 21:20-24 as the disciple whose testimony underlies the gospel. The question of the BD's identity is therefore constrained by this list. Whoever the Beloved Disciple is, he must be one of these seven men.",
      "The process of elimination begins with those disciples the author names explicitly throughout the gospel. A striking feature of the Fourth Gospel is the specificity with which it names its characters — Peter, Andrew, Philip, Thomas, Nathanael and others are all identified by name at various points in the narrative. The consistent and deliberate anonymity of the Beloved Disciple, as we argued in section 3.2, is itself an authorial signal. It follows that those disciples named explicitly in the gospel cannot be the BD. Simon Peter is named throughout and is clearly distinguished from the BD at multiple points in the narrative. Thomas is named explicitly, most memorably in the resurrection appearance of 20:24-28. Nathanael is named at his first encounter with Jesus in 1:45-49 and again in 21:2. These three are therefore eliminated from consideration as candidates for the BD.",
      "That leaves the Sons of Zebedee and two unnamed disciples. Turning to the synoptic list of the twelve in Luke 6:14-16 — 'Simon, whom He also named Peter, and his brother Andrew; and James and John; and Philip and Bartholomew; and Matthew and Thomas; James the son of Alphaeus, and Simon who is called the Zealot; Judas the son of James, and Judas Iscariot, who became a traitor' — we can work through the remaining candidates systematically.",
      "Andrew is named in John's gospel at 1:40, 1:44, 6:8 and 12:22, eliminating him from consideration. Philip is named repeatedly — 1:43, 1:44, 1:45, 6:5, 12:21, 14:8 — eliminating him as well. Matthew wrote his own gospel under his own name, making it highly unlikely that he is the anonymous eyewitness author of the Fourth Gospel. Judas Iscariot is dead. That leaves James son of Zebedee, John son of Zebedee, James son of Alphaeus, Simon the Zealot, Judas son of James, and the two unnamed disciples of John 21 as remaining candidates.",
      "James son of Alphaeus, Simon the Zealot and Judas son of James can be set aside on the straightforward grounds that there is no significant ancient tradition connecting any of them to the authorship of the Fourth Gospel and no evidence placing any of them at Ephesus or within the circle of apostolic leadership that produced the Johannine literature. The two unnamed disciples of John 21 present a theoretical possibility but without any supporting tradition or evidence their candidacy amounts to nothing more than speculation.",
      "That brings us to the Sons of Zebedee — James and John. Here the elimination becomes decisive. Acts 12:1-2 records with brutal brevity: 'Now about that time Herod the king laid hands on some who belonged to the church, to do them harm. He had James the brother of John executed with a sword.' James son of Zebedee was martyred under Herod Agrippa, almost certainly around 44 AD, within little more than a decade of the crucifixion. The Fourth Gospel with its developed theological reflection, its mature Christology and its evident awareness of a long tradition of eyewitness testimony cannot plausibly have been authored by a man who died so early in the apostolic period. James son of Zebedee is therefore eliminated not by inference or probability but by the hard historical fact of his early martyrdom.",
      "That leaves John son of Zebedee. And it is crucial to observe that John son of Zebedee is not merely what remains after everyone else has been crossed off — he is a positively compelling candidate whose identification with the Beloved Disciple is confirmed by a constellation of converging evidence. In the synoptic tradition John is one of the inner three alongside Peter and his brother James — present at the transfiguration, present at Gethsemane, called with his brother a son of thunder. He is among the most prominent figures in the apostolic circle. Yet the Fourth Gospel — which names Peter extensively, which names Andrew, Philip, Thomas and Nathanael — never once names John son of Zebedee. This silence is not accidental. It is the silence of an author who cannot name himself without breaking the self-effacing anonymity he has deliberately maintained throughout his narrative.",
      "The convergence of this internal evidence with the external testimony examined in Chapter 2 is striking. Irenaeus identifies the author as John the disciple of the Lord residing at Ephesus. The process of elimination from the internal evidence of the gospel itself points to John son of Zebedee as the most natural and historically defensible identification of the Beloved Disciple. These two independent lines of evidence — one external, one internal — arrive at the same conclusion by different routes. That convergence is not proof in the strict sense, as we have consistently acknowledged throughout this thesis, but it is precisely the kind of cumulative case that responsible historical argument produces when the evidence is weighed carefully and without prejudice.",
    ],
  },
  {
    heading: "3.4 Jerusalem Knowledge, Topographical Precision and the High Priest Connection",
    level: 3,
    paragraphs: [
      "Among the internal features of the Fourth Gospel that bear directly on the authorship question, two stand out as particularly significant: the gospel's remarkable topographical precision and the Beloved Disciple's personal acquaintance with the high priest recorded in chapter 18. Taken individually each of these features is suggestive — taken together they point toward an author with intimate firsthand knowledge of Jerusalem and its social world that is most naturally explained by direct personal experience.",
      "Richard Bauckham has argued comprehensively that topographical precision is 'just as much a characteristic of John as high Christology or light/darkness imagery or various other ideological features distinctive to this Gospel.' This is not a claim about isolated details but about the systematic character of the gospel as a whole. Bauckham demonstrates through careful comparison with the synoptic gospels that whereas the synoptics frequently leave events unlocated or only vaguely situated — 'a certain village,' 'a certain place,' 'a synagogue' that could be anywhere in Galilee — the Fourth Gospel locates virtually every event with specific precision. As Bauckham observes, 'all events in John's Gospel are located, and most are located quite precisely — in a named town, village, or even more specifically. They are placed not just in Galilee, but in Cana or Capernaum; not just in the temple even but in Solomon's Portico.'",
      "The geographical details unique to the Fourth Gospel are particularly striking. The pool of Bethesda with its five porticoes in 5:2, the pool of Siloam in 9:7, Solomon's Colonnade in 10:23, the specific garden across the Kidron Valley in 18:1 — these are not decorative details borrowed from synoptic tradition. As Bauckham notes, half of John's geographical references are unique to the Fourth Gospel and cannot be explained by dependence on the synoptics. They come from somewhere else. The most natural explanation is firsthand knowledge — the memory of someone who knew Jerusalem and its environs intimately before the destruction of the city in 70 AD.",
      "Bauckham further observes that the two partial exceptions to this topographical precision — the feeding of the five thousand located only generally in the hill country east of the Sea of Galilee and the final resurrection appearance situated simply 'by the Sea of Tiberias' — actually strengthen rather than weaken the eyewitness case. He suggests these imprecise references have 'the effect of reassuring readers that the author does not go beyond his reliable information: in these cases he cannot be more precise but elsewhere he can confidently specify.' This is the scrupulous self-limitation of an honest witness rather than the inventive elaboration of a later theologian.",
      "This topographical precision reaches its most socially revealing expression in the passage concerning the high priest's courtyard in John 18:15-16: 'Simon Peter was following Jesus, and so was another disciple. Now that disciple was known to the high priest, and he entered with Jesus into the courtyard of the high priest, but Peter was standing at the door outside. So the other disciple, who was known to the high priest, went out and spoke to the doorkeeper, and brought Peter in.' The figure identified here as 'another disciple' is the Beloved Disciple — the anonymous eyewitness author maintaining his characteristic self-effacement even at this extraordinary moment.",
      "The details of this passage demand careful attention. The Greek word translated 'known to' is gnostos, implying genuine personal acquaintance rather than mere recognition. This is not someone who had been pointed out to the high priest at a distance — this is someone the high priest actually knew personally. The Beloved Disciple possessed sufficient social standing and personal connection within the high priestly household to enter the courtyard freely with Jesus, to speak with the doorkeeper on Peter's behalf and to secure Peter's admission. These are not the actions of a peripheral or unknown figure — they are the actions of someone with real social capital within the most powerful religious household in Jerusalem.",
      "The incidental detail of the doorkeeper is itself significant. This is precisely the kind of operational specificity that characterizes genuine memory rather than theological invention. A later author constructing this scene for theological purposes would have no reason to mention the doorkeeper — the detail serves no symbolic or theological function. It is simply there because it was there, remembered by the one who spoke to her and brought Peter in.",
      "Taken together the topographical precision of the Fourth Gospel and the high priest connection present a coherent picture of an author who knew Jerusalem and its social world from the inside — someone who had walked its streets, identified its landmarks, and moved within its most significant social circles. This is not the profile of a late Hellenistic community producing a theological document at a remove from the historical events it describes. It is the profile of an eyewitness writing from memory, and it converges naturally with everything else the internal evidence of the gospel has shown us.",
    ],
  },
  {
    heading: "3.5 The Editorial \"We\" of 21:24 and the Ephesian Context",
    level: 3,
    paragraphs: [
      "The closing verses of the Fourth Gospel contain what is perhaps the most explicit internal statement of authorship in the entire New Testament. John 21:24 reads: 'This is the disciple who is testifying about these things and wrote these things, and we know that his testimony is true.' This verse has been the subject of considerable scholarly debate, with particular attention paid to the first person plural 'we know' and what it implies about the composition of the gospel. A careful reading of the verse in its immediate context and in light of the gospel's broader authorial signals reveals not evidence of community composition but a clear identification of the Beloved Disciple as the eyewitness author whose testimony is being vouched for by the apostolic community that surrounded him.",
      "The identification chain that 21:24 establishes is precise and deliberate. As Andreas Köstenberger observes, 'the phrase \"this is the disciple who testifies to these things and who wrote them down\" in 21:24 refers back to \"the disciple whom Jesus loved\" in 21:20, thus identifying the author of John's gospel with the disciple who sat beside Jesus in the upper room according to 13:23 and thus as one of the Twelve and in all likelihood the apostle John.' The verse is not introducing a new figure or a composite authorship — it is closing an identification that has been building throughout the gospel, from the BD's first appearance at 1:35 through his presence at the Last Supper, the cross, the empty tomb and the resurrection appearance on the shore of Tiberias.",
      "The connection between 21:24 and 19:35 is equally important and has been noted by multiple scholars. Köstenberger draws the connection explicitly: 'the phrase resembles the statement in 19:35 — \"the man who saw it has given testimony, and his testimony is true\" — since it is clear that the affirmation in 19:35 must refer to an eyewitness of Jesus's crucifixion, the same arguably pertains to the author of the gospel, who is referred to in 21:24.' The verbal and structural parallels between 19:35 and 21:24 are not accidental. They form an authorial frame around the gospel's narrative — the eyewitness claim at the cross in 19:35 and the authorial identification at the close in 21:24 are the same voice speaking about the same testimony.",
      "This authorial frame extends further back to the prologue. The 'we' of 1:14 — 'we saw His glory' — is the same authorial 'we' that appears in 21:24 — 'we know that his testimony is true.' The gospel opens with the eyewitness community speaking together about what they saw and closes with that same community vouching for the testimony of the one among them who wrote it down. This is a carefully constructed literary and theological inclusio that begins and ends with the same apostolic voice.",
      "The precise meaning of the 'we know' in 21:24 has generated considerable scholarly discussion. Some have argued that it implies a school of writers or a community of composers standing behind the gospel. D.A. Carson addresses this directly, noting that 'even the \"we\" in John 21:24, a difficult pronoun on any view, does not unambiguously argue for a \"school\" of writers' and could 'as easily refer to a group of attesting elders.' This is a crucial observation. The 'we' of 21:24 does not require and does not naturally imply committee authorship — it implies community verification. There is a fundamental difference between a community that composes a document and a community that vouches for the testimony of one of its members.",
      "This reading is confirmed by the immediate context of 21:20-23. The community surrounding the BD had apparently misunderstood Jesus's words about him — believing that Jesus had promised he would not die before the second coming. The author or his editorial circle feels compelled to correct this misunderstanding, noting carefully that 'Jesus did not say to him that he would not die, but only, \"If I want him to remain until I come, what is that to you?\"' This editorial correction demonstrates the editorial honesty of the community surrounding him — they correct a flattering misunderstanding rather than allowing it to stand. And it shows that the 'we' of 21:24 is not an abstract literary device but the voice of a specific historical community with specific memories and specific concerns about the testimony they are vouching for.",
      "The most natural historical context for this community is the apostolic circle at Ephesus that we have already examined in connection with the external evidence. Irenaeus locates John at Ephesus within a living community of apostolic testimony. The Muratorian Fragment describes a process of communal verification before the gospel's publication. Carson's suggestion that the 'we' could refer to 'a group of attesting elders' fits precisely within the Ephesian context — a community of apostolic leaders surrounding John, vouching for his eyewitness testimony and authorizing its publication. Carson further notes the possibility that John 'caused it to be written perhaps through the hands of an amanuensis who enjoyed certain liberties of expression.' This would account for certain features of the gospel's Greek style without surrendering the identification of John son of Zebedee as the eyewitness source and ultimate author of the text.",
    ],
  },
  {
    heading: "3.6 Answering the Objections — Christology, Literary Sophistication and Cultural Distance",
    level: 3,
    paragraphs: [
      "Having established the positive case for apostolic authorship through the eyewitness voice of the prologue, the Beloved Disciple passages, the process of elimination, the topographical precision, the high priest connection and the authorial identification of 21:24, it remains to address the principal objections that critics have raised against identifying John son of Zebedee as the author of the Fourth Gospel. These objections fall into three broad categories: the Christology objection, the literary sophistication objection, and the cultural distance objection.",
      "The most theologically significant objection to apostolic authorship is the claim that the high Christology of the Fourth Gospel represents a theological development so advanced that it cannot plausibly have originated with an eyewitness apostle. This objection assumes that high Christology is a late development, the product of extended theological reflection within a Hellenistic community at a considerable remove from the historical Jesus — an assumption that owes much to Wilhelm Bousset and the history of religions school examined in Chapter 1.",
      "This assumption has been decisively challenged by contemporary scholarship. Larry Hurtado has argued comprehensively that Christ-devotion emerged from within the fiercely exclusivist monotheistic matrix of Second Temple Judaism rather than from Hellenistic influence. The high Christology of the Fourth Gospel is not a Hellenistic importation — it is a Jewish theological development of the most radical and unprecedented kind, emerging from within the apostolic community's reflection on what they had witnessed. George Eldon Ladd makes the complementary point with characteristic precision: 'The Johannine Jesus only affirms more explicitly what is implicit in the Synoptics.' The high Christology of John is not a departure from the apostolic tradition — it is its fullest and most explicit expression, articulated by one who had decades to meditate on what he had witnessed firsthand.",
      "A second objection holds that the literary and theological sophistication of the Fourth Gospel is incompatible with authorship by a Galilean fisherman. This objection is sometimes supported by appeal to Acts 4:13 where Peter and John are described as 'unschooled, ordinary men.' D.A. Carson addresses this objection directly and persuasively. He notes first that the expression in Acts 4:13 'does not mean that Peter and John were illiterate, or profoundly ignorant, but, from the point of view of contemporary theological proficiency, \"untrained laymen,\" not unlike Jesus himself.' The astonishment of the Jerusalem authorities was occasioned precisely by the competence of Peter and John when they should have been relatively ignorant — not by their ignorance when they should have been more competent.",
      "Carson further notes that John came from a family of some economic standing — 'they owned their own boats and employed others' — suggesting that his educational opportunities may well have been better than average. He makes the point memorably: to restrict John's intellectual horizon to the place of his Galilean origin 'when at the time of writing he had not lived there for decades, seems a bit harsh.' He adds the illuminating historical parallel of Rabbi Akiba, 'apparently unlettered until the age of forty' who 'then became one of the greatest rabbis of his generation.' Intellectual and literary development over a lifetime is historically normal and well attested. Carson also allows for the possibility that John 'caused it to be written perhaps through the hands of an amanuensis who enjoyed certain liberties of expression' — accounting for features of the gospel's Greek style without surrendering apostolic authorship.",
      "A third objection holds that the Fourth Gospel's apparent distance from Palestinian Judaism points away from a Palestinian Jewish apostle as its author and toward a later Hellenistic community composition. This objection rests on a misreading of the gospel's character. As we have argued throughout this chapter the Fourth Gospel is not a Hellenistic document with Jewish surface features — it is a profoundly Jewish document whose deepest roots are in the Hebrew Scriptures and the theology of Second Temple Judaism. The Logos of the prologue is rooted in debar Yahweh. The tabernacle allusion of 1:14 invokes the Shekinah glory of Israel's wilderness experience. The gospel's narrative is structured around Jewish feasts. Its 'I am' sayings echo the divine self-identification of Exodus 3:14 and Isaiah 43-48.",
      "The apparent cultural distance is more naturally explained by the Ephesian context than by community composition. Carson observes that John had not lived in Galilee for decades by the time he wrote — he had lived in Judea during the earliest period of the church and then in Ephesus, one of the most cosmopolitan cities in the ancient world. It is also worth noting Carson's pointed observation about Raymond Brown — that in his later work Brown 'changed his mind without answering his own evidence.' The internal evidence for apostolic authorship is strong enough that even its critics have had to wrestle seriously with it before proposing alternatives. The three objections examined in this section represent the most serious challenges to the traditional apostolic authorship of the Fourth Gospel. None of them withstands careful scrutiny when the full historical context of John's life, the Jewish character of the gospel's theology, and the Ephesian setting of its composition are taken properly into account.",
    ],
  },
  {
    heading: "Chapter 4: Ephesus as the Key Context",
    level: 2,
    paragraphs: [],
  },
  {
    heading: "4.1 Beyond \"Irenaeus Said So\" — A Methodological Observation",
    level: 3,
    paragraphs: [
      "Before examining the Ephesian context in detail it is worth making a methodological observation that shapes the argument of this entire chapter. The case for Ephesian provenance and apostolic authorship is sometimes caricatured as a simple appeal to patristic authority — we believe John wrote the gospel at Ephesus because Irenaeus said so. This caricature misrepresents the nature of the argument. The case for Ephesus is not simply an appeal to external testimony but the recognition that the internal evidence of the gospel and the external testimony of the church fathers point independently toward the same historical reality. Ephesus is not merely a conclusion drawn from patristic sources — it is the historical context that most naturally explains the convergence of everything the internal and external evidence has shown us. The gospel itself bears the marks of eyewitness testimony, and the Ephesian tradition helps explain how that testimony was preserved, shaped and transmitted.",
      "This methodological point has direct implications for how we assess D.A. Carson's measured conclusion about Ephesian provenance. Carson surveys the four most commonly proposed locations for the gospel's composition — Alexandria, Antioch, Palestine and Ephesus — and finds the alternatives unconvincing. His dismissal of the Palestine hypothesis is particularly instructive: the assumption that a book about Jesus must have been written in Palestine 'is strange on its very surface' because 'authors have been known to move around.' Carson's conclusion is careful but firm: 'what must be acknowledged is that no other location has the support of the church Fathers; rightly or wrongly, they point to Ephesus.' When the patristic consensus for Ephesus is combined with the internal evidence that converges on the same location, the case becomes considerably stronger than Carson's cautious framing alone might suggest.",
    ],
  },
  {
    heading: "4.2 Ephesus as an Apostolic Hub",
    level: 3,
    paragraphs: [
      "To understand why Ephesus is the natural historical home of the Fourth Gospel it is necessary to appreciate the extraordinary apostolic significance of the city in the first century. Ephesus was not merely a large and cosmopolitan city — it was the most important center of early Christian mission and leadership outside Jerusalem and Antioch, a hub of apostolic activity whose influence radiated across the entire region of Asia Minor.",
      "The apostolic investment in Ephesus begins with Paul. Acts 18:19-21 records his first visit to the city, leaving Priscilla and Aquila there to establish the community before departing. He returns in Acts 19:1-10 for an extended ministry of extraordinary scope — reasoning in the synagogue for three months before withdrawing to the school of Tyrannus where he taught daily for two years, 'so that all who lived in Asia heard the word of the Lord, both Jews and Greeks.' This is not a modest regional mission — it is an apostolic enterprise whose influence spread across an entire province. As Acts 19:26 records, the impact of Paul's Ephesian ministry was felt not only in the city itself but 'in almost all of Asia.' Ephesus was the apostolic center from which the gospel radiated outward across the ancient world.",
      "Paul's farewell address to the Ephesian elders at Miletus in Acts 20:17-38 reveals the depth of this apostolic investment and its implications for the community's future. Paul speaks with the elders of a church he has shepherded with tears and trials for three years, commending them to God and warning them soberly that after his departure 'savage wolves will come in among you, not sparing the flock; and from among your own selves men will arise, speaking perverse things, to draw away the disciples after them.' This warning is significant — Paul is explicitly anticipating that the Ephesian church will face serious doctrinal challenges after his departure and will need strong apostolic leadership to guard the integrity of the gospel.",
      "This charge was taken seriously. When Paul writes to Timothy in 1 Timothy 1:3 he urges him to 'remain on at Ephesus so that you may instruct certain men not to teach strange doctrines' — confirming that the concern for doctrinal integrity at Ephesus was actively being addressed. The book of Revelation confirms that this apostolic character persisted into the later first century. The letter to the church at Ephesus in Revelation 2:1-7 commends the community for testing 'those who call themselves apostles, and they are not, and you found them to be false.' This is a community with strong apostolic discernment — one that takes the verification of apostolic credentials seriously and refuses to accept false claims to apostolic authority. It is precisely this kind of community that would carefully verify and vouch for eyewitness testimony before authorizing its publication.",
    ],
  },
  {
    heading: "4.3 John at Ephesus — The Tradition and Its Significance",
    level: 3,
    paragraphs: [
      "Into this apostolic environment the tradition places John son of Zebedee. As we established in Chapter 2, Irenaeus explicitly locates John at Ephesus — 'John, the disciple of the Lord, who also had leaned upon His breast, did himself publish a Gospel during his residence at Ephesus in Asia' — and grounds this claim in a direct personal chain of memory through Polycarp. Carson notes that Eusebius also records that Asia was allotted to John when the apostles were dispersed at the outbreak of the Jewish War around 66-70 AD, and that while some of Eusebius's apostolic allotments may be legendary 'perhaps this one is reliable since it agrees with other sources, e.g. Irenaeus.' The convergence of Eusebius and Irenaeus on this specific point — despite the general credibility differential between them that we established in Chapter 2 — strengthens the Ephesian tradition considerably.",
      "John's arrival at Ephesus places him in the most significant apostolic center of the ancient world at the most theologically formative period of the early church. He comes not as an obscure figure but as one of the inner three of the apostolic circle — present at the transfiguration, present at Gethsemane, one of the pillars of the Jerusalem church described in Galatians 2:9. His presence at Ephesus would have been an event of the greatest significance for the community there, bringing the living memory of an eyewitness to the ministry, death and resurrection of Jesus into direct contact with the most dynamic center of apostolic mission in the ancient world.",
      "This is the historical environment in which the Fourth Gospel was produced. Not a shadowy Johannine community at a theological remove from the historical Jesus, reconstructed from layers of hypothetical redaction — but a living apostolic community in a major metropolitan center, gathered around an aged eyewitness whose testimony they knew personally and could vouch for directly. The 'we know that his testimony is true' of 21:24 is not an abstract editorial formula — it is the voice of this community, the apostolic circle at Ephesus, speaking from their own knowledge of the man whose testimony they are authorizing.",
    ],
  },
  {
    heading: "4.4 Ephesus Explains the Gospel's Character",
    level: 3,
    paragraphs: [
      "The Ephesian context does not merely corroborate the authorship tradition — it actively explains features of the gospel that have sometimes been cited as evidence against apostolic authorship. The literary and cultural sophistication of the gospel reflects not a departure from its Jewish origins but the natural development of a Jewish apostle who had spent decades in a major Hellenistic urban centre while remaining rooted in the Jewish Scriptures and the apostolic tradition. The gospel's apparent cultural distance from Palestinian Judaism is more naturally explained by the Ephesian context than by community composition.",
      "Furthermore the editorial community implied by 21:24 finds its specific historical identity in the Ephesian apostolic leadership. This is not the elaborate hypothetical Johannine community of Raymond Brown with its multiple layers of composition and redaction — it is the apostolic leadership of the church at Ephesus, the community that Paul charged with guarding the gospel against savage wolves, the community that Revelation commends for testing false apostles, the community that Timothy led under Paul's apostolic authority. This is a community with the apostolic credentials, the doctrinal seriousness and the personal knowledge of John necessary to vouch for his eyewitness testimony with the confidence that 21:24 expresses.",
    ],
  },
  {
    heading: "4.5 The Johannine Epistles and the Ephesian Elder",
    level: 3,
    paragraphs: [
      "A full treatment of the Johannine epistles lies beyond the scope of this thesis, but a brief observation is warranted. The elder figure who speaks with authority in 2 and 3 John — identifying himself simply as 'the elder' without further qualification — fits naturally within the Ephesian apostolic context we have been describing. An aged apostle at Ephesus, known personally to the communities he addresses, speaking with the quiet authority of one whose identity requires no elaboration — this is precisely the profile of John son of Zebedee in his final years at Ephesus. The self-identification as 'the elder' need not imply a figure distinct from the apostle John — it may simply reflect the natural designation of the most senior apostolic figure in the Ephesian community.",
    ],
  },
  {
    heading: "4.6 The Convergence",
    level: 3,
    paragraphs: [
      "The significance of Ephesus for the authorship question is ultimately this: it is the point at which every line of evidence converges. The external testimony of Irenaeus points to Ephesus. The internal evidence of the gospel is consistent with Ephesus. The apostolic character of the Ephesian community explains the editorial verification of 21:24. The doctrinal seriousness of the Ephesian church explains the theological depth and precision of the gospel's Christology. The cosmopolitan environment of Ephesus explains the gospel's engagement with both Jewish and broader Hellenistic audiences without requiring us to posit a late community composition at a remove from the historical events.",
      "The argument for apostolic authorship is not 'Irenaeus said so.' It is that an aged apostle at Ephesus, writing from decades of eyewitness memory and theological reflection, surrounded by an apostolic community that knew him personally and could vouch for his testimony, produced a gospel that bears on every page the marks of what it claims to be — the testimony of one who was there.",
    ],
  },
  {
    heading: "Chapter 5: Weighing the Two Main Positions",
    level: 2,
    paragraphs: [],
  },
  {
    heading: "5.1 The State of the Question",
    level: 3,
    paragraphs: [
      "Having established the external evidence in Chapter 2, the internal evidence in Chapter 3 and the Ephesian context in Chapter 4, we are now in a position to weigh the two most serious scholarly positions on the authorship of the Fourth Gospel against each other. The question is no longer whether the gospel is rooted in genuine eyewitness testimony — the internal evidence examined in Chapter 3 makes that case compellingly — but rather which eyewitness stands behind it. The two most historically serious candidates are John son of Zebedee, the traditional identification supported by Irenaeus and the internal process of elimination, and John the Elder, the alternative proposed most influentially by Richard Bauckham on the basis of his reading of the Papias fragment.",
      "It is worth stating at the outset what this chapter does not claim. It does not claim that the identification of John son of Zebedee as the author of the Fourth Gospel can be proved with certainty. The nature of the evidence does not permit that degree of confidence, and intellectual honesty requires acknowledging as much. What can be claimed, and what this chapter argues, is that the cumulative weight of the external and internal evidence points more naturally and more consistently toward John son of Zebedee than toward any alternative candidate, and that the most influential alternative — Bauckham's Elder John hypothesis — rests on a textual foundation that is considerably less stable than its elegant construction might suggest.",
    ],
  },
  {
    heading: "5.2 Bauckham's Contribution — Eyewitness Memory and the Elder John Hypothesis",
    level: 3,
    paragraphs: [
      "Richard Bauckham's work on Johannine authorship represents one of the most significant contributions to the field in recent decades. His broader argument — that the gospels are rooted in controlled eyewitness testimony transmitted through named individuals within living memory networks rather than through anonymous community tradition — has proven widely influential and commands serious respect even among scholars who do not share all of his conclusions. This eyewitness model is not merely compatible with the argument of this thesis — it actively supports it. Where Bauckham parts company with the traditional position is not on the question of eyewitness testimony but on the identity of the eyewitness.",
      "Bauckham's Elder John hypothesis rests primarily on his reading of the Papias fragment preserved in Eusebius's Ecclesiastical History. The fragment mentions John twice — once in a list of the Lord's disciples alongside Peter, Philip, Thomas, James and Matthew, and once alongside Aristion as one whose words were still being circulated. Bauckham argues that these two references point to two distinct figures — John the apostle and John the Elder — and that it is the latter who is the Beloved Disciple and eyewitness source behind the Fourth Gospel. His most specific grammatical argument is the tense shift between the two references — the first group of disciples are referred to in the past tense while Aristion and John the Elder 'say' in the present tense, suggesting they are still alive and actively transmitting their testimony. This is a genuinely careful reading and the tense shift observation is not trivial. Bauckham's reconstruction is elegant, internally consistent and rooted in serious engagement with the primary sources.",
    ],
  },
  {
    heading: "5.3 The Pressure Points — Where Bauckham's Argument Is Most Vulnerable",
    level: 3,
    paragraphs: [
      "Despite its elegance Bauckham's Elder John hypothesis is built on a narrow textual hinge, and that hinge bears more weight than it can reliably support. The first and most fundamental pressure point is the fragmentary and secondhand nature of the Papias text itself. The fragment comes to us not directly but through Eusebius, a fourth century historian whose motivated interest in finding a second John we have already examined in detail. The tense shift that Bauckham identifies as evidence of two distinct Johns is a real grammatical observation, but its significance depends entirely on the assumption that Papias is being precise and systematic in a way that can survive fragmentary transmission through a tendentious intermediary. That assumption is far from guaranteed.",
      "The second pressure point is the alternative explanation for the double mention of John. The simplest explanation of Papias mentioning John twice is not that he intends two distinct figures but that John was particularly important to him — important enough to mention in both contexts. Bauckham's reading requires us to assume a level of deliberate precision in Papias that the nature of the text does not demand and that the circumstances of its transmission cannot guarantee.",
      "The third and most significant pressure point is that Bauckham's hypothesis requires explaining why Irenaeus — writing in the second century with a direct personal chain of memory through Polycarp to John himself — shows no awareness whatsoever of a distinction between John the apostle and a separate John the Elder. If John the Elder was a figure of sufficient prominence to author the Fourth Gospel, it is extraordinarily difficult to explain why Irenaeus, who had strong personal connections to the Ephesian tradition through Polycarp, would have been entirely unaware of him. Bauckham is compelled to argue that Irenaeus collapsed two distinct Johns into one — but this requires us to believe that a second century bishop with direct personal connections to the Ephesian apostolic tradition made a fundamental error about the identity of the most important figure in that tradition.",
    ],
  },
  {
    heading: "5.4 The Irenaeus Tension — Bauckham's Most Revealing Concession",
    level: 3,
    paragraphs: [
      "The most revealing feature of Bauckham's engagement with the authorship question is not where he is most confident but where he is most constrained. He does not dismiss Irenaeus — he cannot. He acknowledges that Irenaeus is an early witness with genuine historical connections to the Ephesian tradition through Polycarp, and that his testimony carries real historical weight. This acknowledgment is significant because it concedes the central pillar of the traditional authorship argument. Bauckham cannot simply set Irenaeus aside — he must reinterpret him.",
      "This asymmetry is telling. When Bauckham faces the Papias fragment he reads it with confidence and constructs an elaborate hypothesis upon it. When he faces Irenaeus he is compelled to argue that Irenaeus misread his sources, collapsed two figures into one and transmitted a confused tradition. But the credibility differential between these two witnesses runs in precisely the opposite direction from what Bauckham's argument requires. The central question can therefore be stated with precision: is it more plausible that Papias is being precise and systematic in distinguishing two Johns and that Irenaeus subsequently confused them, or that Irenaeus preserves the clearer and more reliable tradition and that Eusebius has read two Johns into a Papias fragment that does not demand that reading? When the question is framed in these terms the answer seems clear.",
    ],
  },
  {
    heading: "5.5 The Traditional Position — A Cumulative Case",
    level: 3,
    paragraphs: [
      "The case for John son of Zebedee as the author of the Fourth Gospel does not rest on any single argument but on the cumulative convergence of multiple independent lines of evidence, each of which points in the same direction. The external evidence establishes that the earliest and most reliable patristic witness — Irenaeus, writing in the second century with a direct personal chain of memory through Polycarp — explicitly identifies the author as John the disciple of the Lord, the Beloved Disciple, residing at Ephesus. The internal evidence establishes through multiple converging arguments that the gospel is rooted in genuine eyewitness testimony from within the apostolic circle. As Köstenberger concludes, the evidence identifies the author 'as one of the Twelve and in all likelihood the apostle John.' The Ephesian context provides the historical environment in which this eyewitness testimony was preserved, shaped and transmitted.",
      "Against this cumulative case Bauckham's Elder John hypothesis offers an elegant but textually fragile alternative built on a contested reading of a fragmentary secondhand source. Its most sophisticated contribution — the eyewitness memory model — actually supports the broader argument of this thesis even while proposing a different identification of the eyewitness. Its weakest point — the dependence on a particular reading of Papias filtered through Eusebius — is precisely where the traditional position is strongest.",
    ],
  },
  {
    heading: "5.6 Conclusion — The Most Defensible Position",
    level: 3,
    paragraphs: [
      "The authorship of the Fourth Gospel cannot be settled with the kind of certainty that admits no reasonable doubt. What can be said — and what this thesis has argued — is that when the evidence is weighed carefully and without prejudice, the traditional identification of John son of Zebedee as the eyewitness author of the Fourth Gospel is the most historically defensible position available. It is more defensible than the Elder John hypothesis because it rests on a broader and more reliable evidentiary foundation. It is more defensible than the various community composition hypotheses because it provides a simpler and more historically grounded explanation of the gospel's character. The gospel itself bears on every page the marks of what it claims to be — the testimony of one who was there, who saw His glory, who leaned on His breast at the Last Supper, who stood at the foot of the cross and watched the blood and water flow, who ran to the empty tomb and believed, who recognized the risen Lord on the shore of the Sea of Tiberias in the early morning light.",
    ],
  },
  {
    heading: "Conclusion",
    level: 2,
    paragraphs: [
      "The authorship of the Fourth Gospel has been one of the most contested questions in New Testament scholarship since the rise of the history of religions school in the nineteenth century. This thesis has argued that when the evidence is examined carefully, freed from the developmental assumptions of the Boussetian framework and weighed according to the actual reliability and proximity of the witnesses, the traditional identification of John son of Zebedee as the eyewitness author of the Fourth Gospel remains the most historically defensible position available.",
      "The cumulative case rests on three converging lines of evidence. The external testimony of Irenaeus, grounded in a direct personal chain of living memory through Polycarp to John himself, provides the most reliable patristic witness to the gospel's authorship — more reliable than the inference Eusebius draws from his reading of the Papias fragment, which reflects a motivated theological agenda rather than disinterested historical transmission. The internal evidence of the gospel itself — the eyewitness voice of the prologue, the Beloved Disciple's presence at every theologically decisive moment of the narrative, the pivotal self-attestation of 19:35, the process of elimination from chapter 21 that points consistently toward John son of Zebedee, the topographical precision and the high priest connection that bear the unmistakable texture of real historical memory, and the authorial identification of 21:24 — converges independently on the same conclusion. And the Ephesian context provides the historical environment in which these two lines of evidence meet — the apostolic hub where an aged eyewitness wrote from decades of memory and theological reflection, surrounded by a community that knew him personally and could vouch for his testimony with the confidence that 21:24 expresses.",
      "The most serious alternative — Richard Bauckham's Elder John hypothesis — represents one of the most sophisticated contributions to Johannine scholarship in recent decades, and his eyewitness memory model has proven widely influential and genuinely illuminating. But his specific identification of the Beloved Disciple with John the Elder rather than John son of Zebedee rests on a narrow textual hinge — a contested reading of a fragmentary secondhand source transmitted through a tendentious historian. When Bauckham faces Irenaeus he cannot dismantle him — he can only reinterpret him. That asymmetry is telling. The most historically substantial witness stands in qualified opposition to Bauckham's reconstruction, and the most textually fragile evidence bears the most weight in sustaining it.",
      "Certainty is not claimed. The nature of the evidence — ancient, fragmentary, transmitted through sources of varying reliability — does not permit it, and intellectual honesty requires acknowledging as much. What has been argued is that the cumulative weight of the evidence points more naturally and more consistently toward John son of Zebedee than toward any alternative, and that the framework which made apostolic authorship seem historically implausible has itself been shown to rest on insecure foundations. With the Boussetian developmental model set aside and the evidence allowed to speak for itself, the testimony of an aged apostle at Ephesus — writing from living memory, vouched for by those who knew him, bearing on every page the marks of one who was there — emerges as the most compelling and most historically defensible account of how the Fourth Gospel came to be.",
      "Further research might profitably examine the Papias fragment in greater text-critical detail, investigate the Ephesian archaeological and historical context more thoroughly, and explore the relationship between the Fourth Gospel and the Johannine epistles with specific attention to the elder figure of 2 and 3 John. Each of these avenues has the potential to shed additional light on the questions this thesis has addressed, and each represents a natural extension of the cumulative argument developed here. The authorship of the Fourth Gospel may never be settled beyond reasonable doubt — but the weight of the evidence, properly assessed, points toward the one who leaned on His breast at the Last Supper, who stood at the foot of the cross and saw the blood and water flow, and who wrote these things down so that we also may believe.",
    ],
  },
  {
    heading: "Bibliography",
    level: 2,
    paragraphs: [
      "Primary Sources",
      "Eusebius of Caesarea. Ecclesiastical History. Translated by Paul L. Maier. Grand Rapids: Kregel Publications, 1999.",
      "Irenaeus of Lyon. Against Heresies. In The Ante-Nicene Fathers, Volume 1. Edited by Alexander Roberts and James Donaldson. Peabody: Hendrickson Publishers, 1994.",
      "The Holy Bible, New American Standard Bible. La Habra: The Lockman Foundation, 1995.",
      "Secondary Sources",
      "Bauckham, Richard. The Testimony of the Beloved Disciple: Narrative, History, and Theology in the Gospel of John. Grand Rapids: Baker Academic, 2007.",
      "Bousset, Wilhelm. Kyrios Christos: A History of the Belief in Christ from the Beginnings of Christianity to Irenaeus. Translated by John E. Steely. Nashville: Abingdon Press, 1970.",
      "Carson, D.A. The Gospel According to John. The Pillar New Testament Commentary. Grand Rapids: Eerdmans, 1991.",
      "Hurtado, Larry W. Lord Jesus Christ: Devotion to Jesus in Earliest Christianity. Grand Rapids: Eerdmans, 2003.",
      "Keener, Craig S. The Gospel of John: A Commentary. 2 vols. Peabody: Hendrickson Publishers, 2003.",
      "Köstenberger, Andreas J. Encountering John: The Gospel in Historical, Literary, and Theological Perspective. Grand Rapids: Baker Academic, 1999.",
      "Ladd, George Eldon. A Theology of the New Testament. Revised edition. Grand Rapids: Eerdmans, 1993.",
    ],
  },
];

let keyCounter = 0;
function nextKey(): string {
  keyCounter += 1;
  return `k${keyCounter}`;
}

function paragraphBlock(text: string, style: string = "normal") {
  return {
    _type: "block",
    _key: nextKey(),
    style,
    markDefs: [],
    children: [
      {
        _type: "span",
        _key: nextKey(),
        text,
        marks: [],
      },
    ],
  };
}

function buildBody() {
  const blocks: unknown[] = [];
  for (const section of SECTIONS) {
    if (section.heading) {
      const style = section.level === 3 ? "h3" : "h2";
      blocks.push(paragraphBlock(section.heading, style));
    }
    for (const p of section.paragraphs) {
      blocks.push(paragraphBlock(p, "normal"));
    }
  }
  return blocks;
}

async function main() {
  console.log("Building post body…");
  const body = buildBody();
  console.log(`Body blocks: ${body.length}`);

  const existing: { _id: string } | null = await client.fetch(
    `*[_type == "post" && slug.current == $slug][0] { _id }`,
    { slug: SLUG }
  );

  const postDoc = {
    _type: "post",
    title: TITLE,
    slug: { _type: "slug", current: SLUG },
    publishedAt: "2026-06-12T12:00:00.000Z",
    author: { _type: "reference", _ref: "author-jude" },
    category: { _type: "reference", _ref: "cat-theology" },
    excerpt: EXCERPT,
    body,
  };

  if (existing) {
    await client.patch(existing._id).set(postDoc).commit();
    console.log(`✅ Updated existing post: ${TITLE}`);
  } else {
    await client.create(postDoc);
    console.log(`✅ Created new post: ${TITLE}`);
  }

  console.log(`\nDone. URL will be: /blog/${SLUG}`);
  console.log(`Allow ~5 minutes for the live site cache to refresh.`);
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
